(deftheme mortimer
  "Mortimer theme")

(custom-theme-set-faces
 'mortimer
  '(default ((t (:inherit nil :stipple nil :background "gray14" :foreground "LightCyan3" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 160 :width normal :foundry "apple" :family "Menlo for Powerline"))))
 '(completion-dynamic-face ((((class color) (background dark)) (:background "darkgrey" :foreground "black"))))
 '(font-lock-comment-face ((((class color) (background dark)) (:foreground "slate blue"))))
 '(highlight ((t (:background "gray17"))))
 '(mmm-code-submode-face ((t (:background "gray20"))))
 '(mmm-default-submode-face ((t (:background "gray9"))))
 '(org-date ((((class color) (background dark)) (:foreground "gray28" :underline t :height 0.9))))
 '(org-done ((t (:foreground "gray35" :strike-through t))))
 '(org-hide ((((background dark)) (:foreground "gray16"))))
 '(org-level-1 ((t (:inherit outline-1 :foreground "LightCyan3" :weight bold :height 1.5))))
 '(org-level-2 ((t (:inherit outline-2 :foreground "LightCyan3"))))
 '(org-special-keyword ((((class color) (min-colors 16) (background dark)) (:foreground "chocolate4" :height 0.9))))
 '(org-tag ((t (:foreground "gray21" :weight bold))))
 '(org-todo ((t (:foreground "red" :weight bold))))
 '(paren-face-match ((((class color)) (:foreground "turquoise"))))
 '(paren-face-match-light ((((class color)) (:foreground "pale turquoise"))))
 '(region ((t (:background "medium blue" :foreground "white"))))
 '(show-paren-match ((t (:bold nil :foreground "white" :background "steel blue"))))
 '(show-paren-mismatch ((t (:bold nil :foreground "white" :background "Red"))))
 '(speedbar-highlight-face ((((class color) (background dark)) (:background "light blue" :foreground "black"))))
 '(helm-selection ((t (:background "gray17" :underline t))))
 '(helm-selection-line ((t (:background "RosyBrown4" :underline t))))
 '(region ((t (:background "gray20" :foreground "LightSkyBlue4"))))
 '(secondary-selection ((t (:background "gray32"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "SteelBlue4"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "wheat2"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "LightSkyBlue3"))))
 '(font-lock-string-face ((t (:foreground "DarkOrange2"))))
 )

(provide-theme 'mortimer)
